apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager-binding
  namespace: coder-workstations
subjects:
- kind: ServiceAccount
  name: coder
  namespace: coder
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
