apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coder-binding
subjects:
- kind: User
  name: coder
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: coder
  apiGroup: rbac.authorization.k8s.io