apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: coder-workstations
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "watch"]
