apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: coder-workstations
  name: pvc-creator
rules:
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "watch"]
